name: Star

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "* * * * *"  # Scheduled to run every minute

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d='DATE '`date '+%Y-%m-%d %H:%M:%S'`
          echo $d > LOG
          
      - name: Commit changes
        run: | 
          git config --local user.email "freefireusa1000@gmail.com"
          git config --local user.name "${{ github.repository_owner }}"
          git add -A
          
          arr=("LOG" "LOG" "LOG" "LOG" "LOG" "LOG" "LOG" "LOG" "LOG" "LOG")
          
          rand=$((RANDOM % ${#arr[@]}))
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.FITHUB_TOKEN }}
          github_url: https://github.com
